# Generated by Django 2.2.9 on 2020-01-09 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webuser',
            name='userauth',
            field=models.CharField(auto_created='user', default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
