# Generated by Django 2.2.9 on 2020-01-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200110_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='myseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_matching', models.BooleanField(default=False, verbose_name='매칭셀러')),
                ('is_corcmp', models.BooleanField(default=False, verbose_name='제휴셀러')),
                ('sellername', models.CharField(max_length=100)),
                ('sellercode', models.CharField(max_length=50)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
