# Generated by Django 2.2.9 on 2020-01-10 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myseller',
            name='is_corcmp',
        ),
        migrations.RemoveField(
            model_name='myseller',
            name='is_matching',
        ),
        migrations.AddField(
            model_name='myseller',
            name='sellertype',
            field=models.CharField(choices=[('매칭셀러', '매칭셀러'), ('자사셀러', '자사셀러'), ('제휴셀러', '제휴셀러')], default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
