# Generated by Django 2.2.9 on 2020-01-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200110_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('disc_price', models.CharField(max_length=10)),
                ('productid', models.CharField(max_length=20)),
                ('vendorid', models.CharField(max_length=20)),
                ('ven_productcd', models.CharField(max_length=30)),
                ('update', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='myseller',
            name='sellertype',
            field=models.CharField(choices=[('1', '매칭셀러'), ('2', '자사셀러'), ('3', '제휴셀러')], max_length=5),
        ),
    ]
